<?php

use console\migrations\baseMigration;

/**
 * Class m200807_130043_create_table_iso_3166_2_estados
 */
class m200807_130043_create_table_iso_3166_2_estados  extends baseMigration
{
    
    const NAME_TABLE='{{%estadosmundo_iso}}';
    
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {

$table=static::NAME_TABLE;
if(!$this->existsTable($table)){
        $this->createTable($table, [
         'id'=>$this->primaryKey(),
           'codpais' => $this->string(3)->append($this->collateColumn()),  
            'codestado' => $this->string(8)->append($this->collateColumn()),  
            'nombreestado' => $this->string(40)->append($this->collateColumn()),  
             ], $this->collateTable());
        
        \Yii::$app->db->createCommand()->
             batchInsert(static::NAME_TABLE,
             ['codpais','codestado','nombreestado'],
             $this->getDataEstados())->execute();
  }
    
    }
	

    
    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        
        if ($this->existsTable(static::NAME_TABLE)) {
            $this->dropTable(static::NAME_TABLE);
        }
    }
    
    private static function  getDataEstados(){             
              return [
['ES','ES-AV','Ávila'],
['ES','ES-BA','Badajoz'],
['ES','ES-PM','Balears (ca) [Baleares]'],
['ES','ES-B','De Barcelona (ca) [Barcelona]'],
['ES','ES-BI','Bizkaia (eu)'],
['ES','ES-BU','Burgos'],
['ES','ES-CC','Cáceres'],
['ES','ES-CA','Cádiz'],
['ES','ES-S','Cantabria'],
['ES','ES-CS','Castellón'],
['ES','ES-CR','Ciudad real'],
['ES','ES-CO','Córdoba'],
['ES','ES-CU','Cuenca'],
['ES','ES-SS','Gipuzkoa (eu)'],
['ES','ES-GI','Girona (ca) [Gerona]'],
['ES','ES-GR','Granada'],
['ES','ES-GU','Guadalajara'],
['ES','ES-H','Huelva'],
['ES','ES-HU','Huesca'],
['ES','ES-J','Jaén'],
['ES','ES-LO','La Rioja'],
['ES','ES-GC','las Palmas'],
['ES','ES-LE','León'],
['ES','ES-L','Lleida (ca) [Lérida]'],
['ES','ES-LU','Lugo (gl) [Lugo]'],
['ES','ES-M','Madrid'],
['ES','ES-MA','Málaga'],
['ES','ES-MU','Murcia'],
['ES','ES-NA','Navarra'],
['ES','ES-OR','Ourense (gl) [Orense]'],
['ES','ES-P','Palencia'],
['ES','ES-PO','Pontevedra (gl) [Pontevedra]'],
['ES','ES-SA','Salamanca'],
['ES','ES-TF','Santa Cruz de Tenerife'],
['ES','ES-SG','Segovia'],
['ES','ES-SE','Sevilla'],
['ES','ES-SO','Soria'],
['ES','EST','Tarragona (ca) [Tarragona]'],
['ES','ES-TE','Teruel'],
['ES','ES-A','Toledo'],
['ES','ES-V','Valencia'],
['ES','ES-VL','València (CA)'],
['ES','ES-VA','Valladolid'],
['ES','ES-ZA','Zamora'],
['ES','ES-Z','Zaragoza'],
['CO','CO-DC','Distrito Capital de Bogotá'],
['CO','CO-AMA','Amazonas'],
['CO','CO-ANT','Antioquia'],
['CO','CO-ARA','Arauca'],
['CO','CO-ATL','Atlántico'],
['CO','CO-BOL','Bolívar'],
['CO','CO-BOY','Boyacá'],
['CO','CO-CAL','Caldas'],
['CO','CO-CAQ','Caquetá'],
['CO','CO-CAS','Casanare'],
['CO','CO-CAU','Cauca'],
['CO','CO-CES','Cesar'],
['CO','CO-COR','Córdoba'],
['CO','CO-CUN','Cundinamarca'],
['CO','CO-CHO','Chocó'],
['CO','CO-GUA','Guainía'],
['CO','CO-GUV','Guaviare'],
['CO','CO-HUI','Huila'],
['CO','CO-LAG','La Guajira'],
['CO','CO-MAG','Magdalena'],
['CO','COMETA','Meta'],
['CO','CO-NAR','Nariño'],
['CO','CO-NSA','Norte de Santander'],
['CO','CO-PUT','Putumayo'],
['CO','CO-QUI','Quindío'],
['CO','CO-RIS','Risaralda'],
['CO','CO-SAP','San Andrés, Providencia y Santa Catalina'],
['CO','CO-SAN','Santander'],
['CO','CO-SUC','Sucre'],
['CO','CO-TOL','Tolima'],
['CO','CO-VAC','Valle del Cauca'],
['CO','CO-VAU','Vaupés'],
['CO','CO-VID','Vichada'],
['DE','DE-BW',' Baden-Württemberg'],
['DE','DE-A',' Bayern'],
['DE','DE-BE',' Berlina'],
['DE','DE-BB',' Brandenburgo'],
['DE','DE-HB',' Bremen'],
['DE','DE-HH',' Hamburgo'],
['DE','DE-HE',' Hessen'],
['DE','DE-MV',' Mecklenburg-Vorpommern'],
['DE','DE-NI',' Niedersachsen'],
['DE','DE-NW',' Nordrhein-Westfalen'],
['DE','DE-RP',' Rheinland-Pfalz'],
['DE','DE-SL',' Sarre'],
['DE','DE-SN',' Sachsen'],
['DE','DE-ST',' Sachsen-Anhalt'],
['DE','DE-SH',' Schleswig-Holstein'],
['DE','DE-TH',' thüringen'],
['FR','FR-01','Ain'],
['FR','FR-02','Aisne'],
['FR','FR-03','Allier'],
['FR','FR-04','Alpes de Alta Provenza'],
['FR','FR-06','Alpes Marítimos'],
['FR','FR-07','Ardèche'],
['FR','FR-08','Ardenas'],
['FR','FR-09','Ariège'],
['FR','FR-10','Aube'],
['FR','FR-11','Aude'],
['FR','FR-12','Aveyron'],
['FR','FR-67','Bajo Rin'],
['FR','FR-13','Bocas del Ródano'],
['FR','FR-14','Calvados'],
['FR','FR-15','Cantal'],
['FR','FR-16','Charente'],
['FR','FR-17','Charente-Maritime'],
['FR','FR-18','Cher'],
['FR','FR-19','Corrèze'],
['FR','FR-2A','Corse-du-Sud'],
['FR','FR-21','Côte-d\'Or'],
['FR','FR-22','Costas de Armor'],
['FR','FR-23','Creuse'],
['FR','FR-79','Deux-Sèvres'],
['FR','FR-24','Dordoña'],
['FR','FR-25','Doubs'],
['FR','FR-26','Drôme'],
['FR','FR-91','Essonne'],
['FR','FR-27','Eure'],
['FR','FR-28','Eure-et-Loir'],
['FR','FR-29','Finisterre'],
['FR','FR-30','Gard'],
['FR','FR-32','Gers'],
['FR','FR-33','Gironda'],
['FR','FR-GP','Guadalupe'],
['FR','FR-2B','Alta Córcega'],
['FR','FR-31','Haute-Garonne'],
['FR','FR-43','Haute-Loire'],
['FR','FR-52','Alto Marne'],
['FR','FR-05','Altos Alpes'],
['FR','FR-70','Alto Saona'],
['FR','FR-74','Alta Saboya'],
['FR','FR-65','Altos Pirineos'],
['FR','FR-87','Alto Vienne'],
['FR','FR-68','Haut-Rhin'],
['FR','FR-92','Hauts-de-Seine'],
['FR','FR-34','Hérault'],
['FR','FR-35','Ille-et-Vilaine'],
['FR','FR-36','Indre'],
['FR','FR-37','Indre-et-Loire'],
['FR','FR-38','Isère'],
['FR','FR-39','Jura'],
['FR','FR-40','Landes'],
['FR','FR-42','Loire'],
['FR','FR-44','Loira Atlántico'],
['FR','FR-45','Loiret'],
['FR','FR-41','Loir-et-Cher'],
['FR','FR-46','Mucho'],
['FR','FR-47','Lot-et-Garonne'],
['FR','FR-48','Lozère'],
['FR','FR-49','Maine-et-Loire'],
['FR','FR-50','Mancha'],
['FR','FR-51','Marne'],
['FR','FR-53','Mayenne'],
['FR','FR-YT','Mayotte'],
['FR','FR-54','Meurthe-et-Moselle'],
['FR','FR-55','Mosa'],
['FR','FR-56','Morbihan'],
['FR','FR-57','Mosela'],
['FR','FR-58','Nièvre'],
['FR','FR-59','Nord'],
['FR','FR-60','Oise'],
['FR','FR-61','Orne'],
['FR','FR-75','París'],
['FR','FR-62','Pas-de-Calais'],
['FR','FR-63','Puy-de-Dôme'],
['FR','FR-64','Pirineos Atlánticos'],
['FR','FR-66','Pirineos Orientales'],
['FR','FR-RE','La Reunión'],
['FR','FR-69','Ródano'],
['FR','FR-71','Saône-et-Loire'],
['FR','FR-72','Sarthe'],
['FR','FR-73','Saboya'],
['FR','FR-77','Sena y Marne'],
['FR','FR-76','Sena Marítimo'],
['FR','FR-93','Sena-Saint-Denis'],
['FR','FR-80','Somme'],
['FR','FR-81','Tarn'],
['FR','FR-82','Tarn-et-Garonne'],
['FR','FR-90','Territorio de Belfort'],
['FR','FR-94','Val-de-Marne'],
['FR','FR-95','Valle del Oise'],
['FR','FR-83','var'],
['FR','FR-84','Vaucluse'],
['FR','FR-85','Vendée'],
['FR','FR-86','Vienne'],
['FR','FR-88','Vosgos'],
['FR','FR-89','Yonne'],
['FR','FR-78','Yvelines'],
['AR','ARCO',' Ciudad Autónoma de Buenos Aires'],
['AR','AR-B',' Buenos Aires'],
['AR','ARCA',' Catamarca'],
['AR','AR-H',' Chaco'],
['AR','AR-T',' Chubut'],
['AR','AR-X',' Córdoba'],
['AR','AR-W',' Corrientes'],
['AR','SON',' Entre Ríos'],
['AR','AR-P',' Formosa'],
['AR','AR-Y',' Jujuy'],
['AR','AR-L',' La Pampa'],
['AR','AR-F',' La Rioja'],
['AR','BRAZO',' Mendoza'],
['AR','AR-N',' Misiones'],
['AR','AR-Q',' Neuquén'],
['AR','AR-R',' Río Negro'],
['AR','ARA',' Salta'],
['AR','AR-J',' San Juan'],
['AR','AR-D',' San Luis'],
['AR','AR-Z',' Santa Cruz'],
['AR','AR-S',' Santa Fe'],
['AR','AR-G',' Santiago del Estero'],
['AR','AR-V',' tierra del Fuego'],
['AR','ART',' Tucumán'],
['UY','UY-AR',' Artigas'],
['UY','UY-CA',' Canelones'],
['UY','UY-CL',' Cerro Largo'],
['UY','UY-CO',' Colonia'],
['UY','UY-DU',' Durazno'],
['UY','UY-FS',' Flores'],
['UY','UY-FD',' Florida'],
['UY','UY-LA',' Lavalleja'],
['UY','UY-MA',' Maldonado'],
['UY','UY-MO',' Montevideo'],
['UY','UY-PA',' Paysandú'],
['UY','UY-RN',' Río Negro'],
['UY','UY-RV',' Rivera'],
['UY','UY-RO',' Rocha'],
['UY','UY-SA',' Salto'],
['UY','UY-SJ',' San José'],
['UY','UY-SO',' Soriano'],
['UY','UY-TA',' Tacuarembó'],
['UY','UY-TT',' Treinta y Tres'],
['MX','MX-CMX','Ciudad de México'],
['MX','MX-AGU','Aguascalientes'],
['MX','MX-BCN','Baja California'],
['MX','MX-BCS','Baja California Sur'],
['MX','MX-CAM','Campeche'],
['MX','MX-COA','Coahuila de Zaragoza'],
['MX','MX-COL','Colima'],
['MX','MX-CHP','Chiapas'],
['MX','MX-CHH','Chihuahua'],
['MX','MX-DUR','Durango'],
['MX','MX-GUA','Guanajuato'],
['MX','MX-GRO','Guerrero'],
['MX','MX-HID','Hidalgo'],
['MX','MX-JAL','Jalisco'],
['MX','MX-MEX','México'],
['MX','MX-MIC','Michoacán de Ocampo'],
['MX','MX-MOR','Morelos'],
['MX','MX-NAY','Nayarit'],
['MX','MX-NLE','Nuevo León'],
['MX','MX-OAX','Oaxaca'],
['MX','MX-PUE','Puebla'],
['MX','MX-QUE','Querétaro'],
['MX','MX-ROO','Quintana Roo'],
['MX','MX-SLP','San Luis Potosí'],
['MX','MX-SIN','Sinaloa'],
['MX','MX-SON','Sonora'],
['MX','MX-TAB','Tabasco'],
['MX','MX-TAM','Tamaulipas'],
['MX','MX-TLA','Tlaxcala'],
['MX','MX-VER','Veracruz de Ignacio de la Llave'],
['MX','MX-YUC','Yucatán'],
['MX','MX-ZAC','Zacatecas'],
           ];              
              
              
    }
    
    
    
}
